import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'tech-harbor-laptop-x1',
    name: 'لابتوب TechHarbor X1',
    description: 'أداء قوي وتصميم أنيق.',
    longDescription: 'يتميز لابتوب TechHarbor X1 بمعالج فائق السرعة وشاشة عالية الدقة، مما يجعله الخيار المثالي للمحترفين والمبدعين. بفضل تصميمه النحيف وخفة وزنه، يمكنك حمله معك أينما ذهبت.',
    price: 4500,
    image: 'https://placehold.co/600x400/e63946/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'New',
    featured: true,
    featured2: false,
  },
  {
    id: '2',
    slug: 'aura-phone-pro',
    name: 'هاتف Aura Pro',
    description: 'كاميرا مذهلة وشاشة غامرة.',
    longDescription: 'التقط صورًا احترافية مع هاتف Aura Pro المزود بنظام كاميرا متطور. استمتع بمشاهدة أفلامك وألعابك المفضلة على شاشته الكبيرة والنابضة بالحياة.',
    price: 3200,
    image: 'https://placehold.co/600x400/1d3557/ffffff?text=Phone',
    category: 'Phones',
    condition: 'New',
    featured: true,
    featured2: true,
  },
  {
    id: '3',
    slug: 'connect-laptop-5',
    name: 'لابتوب Connect 5',
    description: 'موثوقية عالية للاستخدام اليومي.',
    longDescription: 'لابتوب Connect 5 هو رفيقك المثالي للمهام اليومية، سواء للدراسة أو العمل. يوفر أداءً مستقرًا وعمر بطارية طويل لتظل منتجًا طوال اليوم.',
    price: 2800,
    image: 'https://placehold.co/600x400/457b9d/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'Used',
    featured: true,
    featured2: false,
  },
  {
    id: '4',
    slug: 'pixel-perfect-phone',
    name: 'هاتف PixelPerfect',
    description: 'تجربة أندرويد نقية.',
    longDescription: 'استمتع بأحدث ميزات نظام أندرويد مع هاتف PixelPerfect. يقدم تحديثات سريعة وواجهة نظيفة، بالإضافة إلى كاميرا ذكية تلتقط أدق التفاصيل.',
    price: 2500,
    image: 'https://placehold.co/600x400/f4a261/ffffff?text=Phone',
    category: 'Phones',
    condition: 'New',
    featured: false,
    featured2: true,
  },
  {
    id: '5',
    slug: 'zenith-laptop-slim',
    name: 'لابتوب Zenith Slim',
    description: 'نحيف للغاية وقوي بشكل مدهش.',
    longDescription: 'يجمع لابتوب Zenith Slim بين التصميم الأنيق والأداء القوي. إنه الخيار الأمثل لمن يبحث عن جهاز محمول وخفيف دون التنازل عن الأداء.',
    price: 5200,
    image: 'https://placehold.co/600x400/2a9d8f/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'New',
    featured: false,
    featured2: true,
  },
  {
    id: '6',
    slug: 'nova-phone-x',
    name: 'هاتف Nova X',
    description: 'بطارية تدوم طويلاً.',
    longDescription: 'لا تقلق بشأن نفاد البطارية مع هاتف Nova X. صُمم ليدوم طوال اليوم مع استخدامك المكثف، لتظل على اتصال دائمًا.',
    price: 1900,
    image: 'https://placehold.co/600x400/e76f51/ffffff?text=Phone',
    category: 'Phones',
    condition: 'Used',
    featured: false,
    featured2: true,
  },
  {
    id: '7',
    slug: 'power-book-pro-2',
    name: 'لابتوب PowerBook Pro 2',
    description: 'محطة عمل محمولة.',
    longDescription: 'أطلق العنان لإبداعك مع لابتوب PowerBook Pro 2. يوفر قوة معالجة هائلة ورسومات مذهلة لتحرير الفيديو والتصميم ثلاثي الأبعاد.',
    price: 7500,
    image: 'https://placehold.co/600x400/e63946/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'New',
    featured: false,
    featured2: true,
  },
  {
    id: '8',
    slug: 'galaxy-fold-z',
    name: 'هاتف Galaxy Fold Z',
    description: 'مستقبل الهواتف القابلة للطي.',
    longDescription: 'جرب المستقبل مع هاتف Galaxy Fold Z. شاشة قابلة للطي تمنحك تجربة مشاهدة غامرة بحجم الجهاز اللوحي في جيبك.',
    price: 6800,
    image: 'https://placehold.co/600x400/1d3557/ffffff?text=Phone',
    category: 'Phones',
    condition: 'New',
    featured: false,
    featured2: true,
  },
   {
    id: '9',
    slug: 'streamline-laptop-air',
    name: 'لابتوب Streamline Air',
    description: 'خفيف كالريشة، سريع كالبرق.',
    longDescription: 'لابتوب Streamline Air مصمم للتنقل. بوزنه الخفيف وأدائه السريع، يعد الخيار المثالي للطلاب والمسافرين الدائمين.',
    price: 3800,
    image: 'https://placehold.co/600x400/457b9d/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'New',
    featured: false,
    featured2: true,
  },
  {
    id: '10',
    slug: 'pulse-phone-gamer',
    name: 'هاتف Pulse Gamer',
    description: 'مصمم خصيصًا للألعاب.',
    longDescription: 'سيطر على ساحة اللعب مع هاتف Pulse Gamer. يتميز بمعدل تحديث عالٍ ونظام تبريد متقدم لتجربة لعب سلسة وخالية من التأخير.',
    price: 3500,
    image: 'https://placehold.co/600x400/f4a261/ffffff?text=Phone',
    category: 'Phones',
    condition: 'New',
    featured: false,
    featured2: true,
  },
  {
    id: '11',
    slug: 'titan-workstation-laptop',
    name: 'لابتوب Titan Workstation',
    description: 'أداء لا هوادة فيه للمهام الصعبة.',
    longDescription: 'لا توجد مهمة كبيرة جدًا على لابتوب Titan Workstation. مزود بأقوى المكونات لمعالجة البيانات الضخمة والمحاكاة المعقدة.',
    price: 9500,
    image: 'https://placehold.co/600x400/2a9d8f/ffffff?text=Laptop',
    category: 'Laptops',
    condition: 'Used',
    featured: false,
    featured2: true,
  },
  {
    id: '12',
    slug: 'echo-phone-5g',
    name: 'هاتف Echo 5G',
    description: 'سرعات فائقة وتصميم عصري.',
    longDescription: 'ابق متصلاً بسرعات 5G المذهلة مع هاتف Echo 5G. قم بتنزيل الأفلام في ثوانٍ واستمتع ببث مباشر فائق الوضوح.',
    price: 2900,
    image: 'https://placehold.co/600x400/e76f51/ffffff?text=Phone',
    category: 'Phones',
    condition: 'New',
    featured: false,
    featured2: false,
  },
];
